export type QueryGenerator =
    | 'allcategories'
    | 'alldeletedrevisions'
    | 'allfileusages'
    | 'allimages'
    | 'alllinks'
    | 'allpages'
    | 'allredirects'
    | 'allrevisions'
    | 'alltransclusions'
    | 'backlinks'
    | 'categories'
    | 'categorymembers'
    | 'deletedrevisions'
    | 'duplicatefiles'
    | 'embeddedin'
    | 'exturlusage'
    | 'fileusage'
    | 'images'
    | 'imageusage'
    | 'iwbacklinks'
    | 'langbacklinks'
    | 'links'
    | 'linkshere'
    | 'messagecollection'
    | 'mostviewed'
    | 'pageswithprop'
    | 'prefixsearch'
    | 'protectedtitles'
    | 'querypage'
    | 'random'
    | 'recentchanges'
    | 'redirects'
    | 'revisions'
    | 'search'
    | 'templates'
    | 'transcludedin'
    | 'watchlist'
    | 'watchlistraw'
    | 'wblistentityusage';

export type QueryGeneratorParams = {
    allcategories: any;
    alldeletedrevisions: any;
    allfileusages: any;
    allimages: any;
    alllinks: any;
    allpages: any;
    allredirects: any;
    allrevisions: any;
    alltransclusions: any;
    backlinks: any;
    categories: any;
    categorymembers: any;
    deletedrevisions: any;
    duplicatefiles: any;
    embeddedin: any;
    exturlusage: any;
    fileusage: any;
    images: any;
    imageusage: any;
    iwbacklinks: any;
    langbacklinks: any;
    links: any;
    linkshere: any;
    messagecollection: any;
    mostviewed: any;
    pageswithprop: any;
    prefixsearch: any;
    protectedtitles: any;
    querypage: any;
    random: any;
    recentchanges: any;
    redirects: any;
    revisions: any;
    search: any;
    templates: any;
    transcludedin: any;
    watchlist: any;
    watchlistraw: any;
    wblistentityusage: any;
};

export type QueryGeneratorResult = {
    allcategories: any;
    alldeletedrevisions: any;
    allfileusages: any;
    allimages: any;
    alllinks: any;
    allpages: any;
    allredirects: any;
    allrevisions: any;
    alltransclusions: any;
    backlinks: any;
    categories: any;
    categorymembers: any;
    deletedrevisions: any;
    duplicatefiles: any;
    embeddedin: any;
    exturlusage: any;
    fileusage: any;
    images: any;
    imageusage: any;
    iwbacklinks: any;
    langbacklinks: any;
    links: any;
    linkshere: any;
    messagecollection: any;
    mostviewed: any;
    pageswithprop: any;
    prefixsearch: any;
    protectedtitles: any;
    querypage: any;
    random: any;
    recentchanges: any;
    redirects: any;
    revisions: any;
    search: any;
    templates: any;
    transcludedin: any;
    watchlist: any;
    watchlistraw: any;
    wblistentityusage: any;
};
