export type QueryList =
    | 'abusefilters'
    | 'abuselog'
    | 'allcategories'
    | 'alldeletedrevisions'
    | 'allfileusages'
    | 'allimages'
    | 'alllinks'
    | 'allpages'
    | 'allredirects'
    | 'allrevisions'
    | 'alltransclusions'
    | 'allusers'
    | 'backlinks'
    | 'betafeatures'
    | 'blocks'
    | 'categorymembers'
    | 'centralnoticeactivecampaigns'
    | 'centralnoticelogs'
    | 'checkuser'
    | 'checkuserlog'
    | 'embeddedin'
    | 'extdistrepos'
    | 'exturlusage'
    | 'filearchive'
    | 'gadgetcategories'
    | 'gadgets'
    | 'globalallusers'
    | 'globalblocks'
    | 'globalgroups'
    | 'imageusage'
    | 'iwbacklinks'
    | 'langbacklinks'
    | 'linterrors'
    | 'logevents'
    | 'messagecollection'
    | 'mostviewed'
    | 'mystashedfiles'
    | 'pagepropnames'
    | 'pageswithprop'
    | 'prefixsearch'
    | 'protectedtitles'
    | 'querypage'
    | 'random'
    | 'recentchanges'
    | 'search'
    | 'tags'
    | 'threads'
    | 'usercontribs'
    | 'users'
    | 'watchlist'
    | 'watchlistraw'
    | 'wblistentityusage'
    | 'wikisets';

export type QueryListParams = {
    abusefilters: any;
    abuselog: any;
    allcategories: any;
    alldeletedrevisions: any;
    allfileusages: any;
    allimages: any;
    alllinks: any;
    allpages: any;
    allredirects: any;
    allrevisions: any;
    alltransclusions: any;
    allusers: any;
    backlinks: any;
    betafeatures: any;
    blocks: any;
    categorymembers: any;
    centralnoticeactivecampaigns: any;
    centralnoticelogs: any;
    checkuser: any;
    checkuserlog: any;
    embeddedin: any;
    extdistrepos: any;
    exturlusage: any;
    filearchive: any;
    gadgetcategories: any;
    gadgets: any;
    globalallusers: any;
    globalblocks: any;
    globalgroups: any;
    imageusage: any;
    iwbacklinks: any;
    langbacklinks: any;
    linterrors: any;
    logevents: any;
    messagecollection: any;
    mostviewed: any;
    mystashedfiles: any;
    pagepropnames: any;
    pageswithprop: any;
    prefixsearch: any;
    protectedtitles: any;
    querypage: any;
    random: any;
    recentchanges: any;
    search: any;
    tags: any;
    threads: any;
    usercontribs: any;
    users: any;
    watchlist: any;
    watchlistraw: any;
    wblistentityusage: any;
    wikisets: any;
};

export type QueryListResult = {
    abusefilters: any;
    abuselog: any;
    allcategories: any;
    alldeletedrevisions: any;
    allfileusages: any;
    allimages: any;
    alllinks: any;
    allpages: any;
    allredirects: any;
    allrevisions: any;
    alltransclusions: any;
    allusers: any;
    backlinks: any;
    betafeatures: any;
    blocks: any;
    categorymembers: any;
    centralnoticeactivecampaigns: any;
    centralnoticelogs: any;
    checkuser: any;
    checkuserlog: any;
    embeddedin: any;
    extdistrepos: any;
    exturlusage: any;
    filearchive: any;
    gadgetcategories: any;
    gadgets: any;
    globalallusers: any;
    globalblocks: any;
    globalgroups: any;
    imageusage: any;
    iwbacklinks: any;
    langbacklinks: any;
    linterrors: any;
    logevents: any;
    messagecollection: any;
    mostviewed: any;
    mystashedfiles: any;
    pagepropnames: any;
    pageswithprop: any;
    prefixsearch: any;
    protectedtitles: any;
    querypage: any;
    random: any;
    recentchanges: any;
    search: any;
    tags: any;
    threads: any;
    usercontribs: any;
    users: any;
    watchlist: any;
    watchlistraw: any;
    wblistentityusage: any;
    wikisets: any;
};
