export type QueryList =
    | 'abusefilters'
    | 'abuselog'
    | 'allcategories'
    | 'alldeletedrevisions'
    | 'allfileusages'
    | 'allimages'
    | 'alllinks'
    | 'allpages'
    | 'allredirects'
    | 'allrevisions'
    | 'alltransclusions'
    | 'allusers'
    | 'backlinks'
    | 'betafeatures'
    | 'blocks'
    | 'categorymembers'
    | 'centralnoticeactivecampaigns'
    | 'centralnoticelogs'
    | 'checkuser'
    | 'checkuserlog'
    | 'embeddedin'
    | 'extdistrepos'
    | 'exturlusage'
    | 'filearchive'
    | 'gadgetcategories'
    | 'gadgets'
    | 'globalallusers'
    | 'globalblocks'
    | 'globalgroups'
    | 'imageusage'
    | 'iwbacklinks'
    | 'langbacklinks'
    | 'linterrors'
    | 'logevents'
    | 'messagecollection'
    | 'mostviewed'
    | 'mystashedfiles'
    | 'pagepropnames'
    | 'pageswithprop'
    | 'prefixsearch'
    | 'protectedtitles'
    | 'querypage'
    | 'random'
    | 'recentchanges'
    | 'search'
    | 'tags'
    | 'threads'
    | 'usercontribs'
    | 'users'
    | 'watchlist'
    | 'watchlistraw'
    | 'wblistentityusage'
    | 'wikisets';

// --- Params -------------------------

export type QueryListParams<T extends QueryList> = any;

// --- Result -------------------------

export type QueryListResult<T extends QueryList> = any;
