export type QueryProp =
    | 'categories'
    | 'categoryinfo'
    | 'cirrusbuilddoc'
    | 'cirruscompsuggestbuilddoc'
    | 'cirrusdoc'
    | 'contributors'
    | 'deletedrevisions'
    | 'duplicatefiles'
    | 'extlinks'
    | 'extracts'
    | 'fileusage'
    | 'globalusage'
    | 'imageinfo'
    | 'images'
    | 'info'
    | 'iwlinks'
    | 'langlinks'
    | 'links'
    | 'linkshere'
    | 'mmcontent'
    | 'pageimages'
    | 'pageprops'
    | 'pageterms'
    | 'pageviews'
    | 'redirects'
    | 'revisions'
    | 'stashimageinfo'
    | 'templates'
    | 'transcludedin'
    | 'transcodestatus'
    | 'videoinfo'
    | 'wbentityusage';

export type QueryPropParams = {
    categories: any;
    categoryinfo: any;
    cirrusbuilddoc: any;
    cirruscompsuggestbuilddoc: any;
    cirrusdoc: any;
    contributors: any;
    deletedrevisions: any;
    duplicatefiles: any;
    extlinks: any;
    extracts: any;
    fileusage: any;
    globalusage: any;
    imageinfo: any;
    images: any;
    info: any;
    iwlinks: any;
    langlinks: any;
    links: any;
    linkshere: any;
    mmcontent: any;
    pageimages: any;
    pageprops: any;
    pageterms: any;
    pageviews: any;
    redirects: any;
    revisions: any;
    stashimageinfo: any;
    templates: any;
    transcludedin: any;
    transcodestatus: any;
    videoinfo: any;
    wbentityusage: any;
};

export type QueryPropResult = {
    categories: any;
    categoryinfo: any;
    cirrusbuilddoc: any;
    cirruscompsuggestbuilddoc: any;
    cirrusdoc: any;
    contributors: any;
    deletedrevisions: any;
    duplicatefiles: any;
    extlinks: any;
    extracts: any;
    fileusage: any;
    globalusage: any;
    imageinfo: any;
    images: any;
    info: any;
    iwlinks: any;
    langlinks: any;
    links: any;
    linkshere: any;
    mmcontent: any;
    pageimages: any;
    pageprops: any;
    pageterms: any;
    pageviews: any;
    redirects: any;
    revisions: any;
    stashimageinfo: any;
    templates: any;
    transcludedin: any;
    transcodestatus: any;
    videoinfo: any;
    wbentityusage: any;
};
